name: 'Saludo Desde Docker'
description: 'Hace un Saludo desde el contenedor'
inputs:
  quien:
    description: 'Para quién es el Saludo'
    required: true
    default: 'Todos'
outputs:
 hora:
   description: 'la hora del saludito'
runs:
  using: 'Docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.quien }}
