name: 'Ejecutar Docker'
on: push
jobs:
  saludar:
    runs-on: ubuntu-latest
    name: 'Tarea para saludarme'
    steps:
     - name: 'Ejecutar la acción del Docker'
       id: hola
       uses: Beto281980/PRACTICA_CONTENEDORES-DOCKERS-_ALBERTO@v1
       with:
         quien: 'Beto'
     - name: 'Mostrar la hora obtenida'
       run: echo "La hora obtenida fue ${{ steps.hola.outputs.hora }}"
